openapi: 3.0.0

info:
  title: watagit / React Go Todo API
  description: React Go Todo API仕様書
  version: 1.0.0

tags:
  - name: todos
    description: todo関連API

paths:

  /v1/todos:
    get:
      summary: Get all todo
      description: 全てのtodo情報を取得します．
      tags:
        - todos
      parameters: []
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Todo'
                example:
                  - id: 1
                    content: 砂糖を買う
                    completed: false
                  - id: 2
                    content: 課題を終わらせる
                    completed: false
                  - id: 3
                    content: 歯医者に行く
                    completed: false
    post:
      summary: Create new todo
      description: todo情報を作成します．
      tags:
        - todos
      parameters: []
      requestBody:
        description: todoのオブジェクト
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Todo'
            example:
              id: 4
              content: 寿司を食べる
              completed: false
      responses:
        '201':
          description: Successful create

  /v1/todos/{id}:
    get:
      summary: Get single todo
      description: 任意のtodoの情報を取得します．
      tags:
        - todos
      parameters:
        - name: id
          in: path
          description: todo id
          required: true
          schema:
            type: integer
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: object
                items:
                  $ref: '#/components/schemas/Todo'
                example:
                  id: 1
                  content: 砂糖を買う
                  completed: false
        '409':
          description: The resource already exist
    delete:
      summary: Delete single todo
      description: 任意のtodoの情報を削除します．
      tags:
        - todos
      responses:
        '204':
          description: Deleted
        '404':
          description: id not found

  /v1/todos/{id}/toggle-completed:
    patch:
      summary: Toggle single todo's completed
      description: 任意のtodoのcompletedを切り替えます．
      tags:
        - todos
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: integer
      responses:
        '200':
          description: OK
        '204':
          description: Conflict


components:
  schemas:
    Todo:
      type: object
      required:
        - id
      properties:
        id:
          type: integer
          format: int64
        content:
          type: string
        completed:
          type: boolean
